plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

javafx {
    version = javafxVersion
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'com.financeiramente.desktop.app.Main'
}

dependencies {
    implementation project(':core')
    implementation "org.xerial:sqlite-jdbc:${sqliteJdbcVersion}"
}
